### ISSUE TITLE
ESLint couldn't find the config "typescript-enum/recommended" 

### ISSUE THREAD

**Issue by wormyy** [shian15810/eslint-plugin-typescript-enum#3]
Hi, thanks for the plugin. I tried it, but I got this:

```
ESLint couldn't find the config "typescript-enum/recommended" to extend from. Please check that the name of the config is correct.

The config "typescript-enum/recommended" was referenced from the config file in "/Users/julius_retzer/work/epam/web-order-ahead/.eslintrc.js".
```

It seems like in the node modules there's missing `index.js`

**Comment by shian15810** [comment]
@wormyy Thanks for reporting. Are you using npm or yarn? And can you provide me the version of it? So that I can try to reproduce this.

**Comment by scrpthub** [comment]
I changed my extends configuration in .eslintrc.js from `"typescript-enum/recommended"` to `"plugin:typescript-enum/recommended"` and it seems to work

**Comment by shian15810** [comment]
Thanks @scrpthub it's my bad on the documentation side. Will update the README later!

**Comment by shian15810** [comment]
Solved this via https://github.com/shian15810/eslint-plugin-typescript-enum/commit/b7e5ec4c6a2971fdef2d6f64de91ee0fac63b750!
